/*
-- Query: SELECT * FROM schema_b.gk_inventory
LIMIT 0, 10000

-- Date: 2024-05-13 11:08
*/
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (1,'Cucmuber','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (2,'Sour Cream James Farm','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (3,'Mt. Olive Dill chips','0','0','Other');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (4,'Silver Source Mayo','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (5,'New Eng. Garlic Sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (6,'Tableside Caesar Village Garden','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (7,'West Creek Cocktail Sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (8,'Ranch','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (9,'W.C thousand Island','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (10,'W.C. Yellow Mustard','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (11,'V.G Tuscany Balsamic Vinaigrette','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (12,'Cilantro','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (13,'Onions RTU','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (14,'Corn tortillas Milagro','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (15,'Tropicana Big no pulp','0','0','Juice');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (16,'Tropicana 12OZ N.P - For no pulp','0','0','Juice');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (17,'425g Country Butter Members Mark','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (18,'19kg CC butter','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (19,'Pacific Romaine Hearts','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (20,'Jalapenos','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (21,'Domninicks Jumbo Carrots','0','00','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (22,'Oranges','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (23,'Serrano Peppers','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (24,'Pineapple','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (25,'Parsley','0','0','Herbs');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (26,'Frutas Finas Tan. Avocado','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (27,'1lb Rosemary Jetro','0','0','Other');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (28,'Bell Peppers','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (29,'Crimon ™ Tomatoes','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (30,'Corn','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (31,'Black pepper','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (32,'Ground Black pepper','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (33,'cinnamon sticks','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (34,'Cumin','0','0','Herbs');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (35,'Pure sesame oil roland','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (36,'Whole Black Pepper Chefs Quality','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (37,'Whole allspire Chefs Quality','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (38,'Mustard Seed Chefs Quality','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (39,'Hulled Sesame seed Chefs Quality','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (40,'Whole Cloves Chefs Quality','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (41,'Kikkoman soy sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (42,'Members Mark Maraschino Cherries','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (43,'Granulated Onion','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (44,'Parsley flake Roma','0','0','Herbs');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (45,'Chili Powder','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (46,'Butcher Black Pepper','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (47,'Bay leaves','0','0','Herbs');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (48,'Ground Black Pepper','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (49,'Oregano','0','0','Herbs');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (50,'pot. Pearls Mashed Potato','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (51,'chile Arrol','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (52,'Royal Baking powder','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (53,'Baking Soda','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (54,'W.C. Ranch Mix','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (55,'McC imitation vinila Flavoring','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (56,'Zest Cracker og','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (57,'West Creek Pure Applw cider vinegar','00','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (58,'Mango Habanero Sweet baby ray\'s','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (59,'PMC syrup og','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (60,'Contigo whole peeled tomato 25.90','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (61,'La Castanza whole green tomato','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (62,'L.C. Jalapenos','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (63,'CQ sweet pea','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (64,'Tomate puree WC','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (65,'Empartod Mushroom','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (66,'Pineapple tidbits','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (67,'Alfredo Land of Lakes','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (68,'Camino','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (69,'arinara Sauce','0','00','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (70,'Tortilla Chips','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (71,'Shrimp White','0','0','Seafood');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (72,'Salmon','0','0','Seafood');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (73,'Pork Chorizo','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (74,'Chicken Fat','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (75,'Chicken','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (76,'Ribeye Steak','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (77,'Eggs','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (78,'Ground Beef','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (79,'Philly cream cheese','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (80,'Mazzerella Shreeded Cheese','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (81,'Coconut','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (82,'pepperoni','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (83,'American Cheese Ultimmelt','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (84,'Cream Cheese Blend','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (85,'Heavy Cream','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (86,'Coffe Creamer','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (87,'Beans','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (88,'White Grapefruit Juice','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (89,'Yellow Sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (90,'White Hot Dog Buns','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (91,'Jumbo slice Hambuger Buns','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (92,'Green Sauce','0','00','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (93,'Sour cream','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (94,'Cheese Dip','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (95,'Heinz 47','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (96,'Valentina Salsa','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (97,'A1','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (98,'Marten Salt','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (99,'Cramberry See Cocktail','0','0','Other');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (100,'Corn Starch','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (101,'Yellow Mustard','0','00','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (102,'Eggs and Milk replacements','0','0','Other');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (103,'Parne Italian Tubie','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (104,'SBR BBQ sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (105,'Italian Dressing','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (106,'Texas Pete Buffal Chicken wing sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (107,'WC wing sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (108,'Kems Boom Boom Sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (109,'Vg traditional Harney Mustard','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (110,'Drill. Buttery Flavored Oil','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (111,'Jasmine Rice','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (112,'Flour','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (113,'Pink Salt','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (114,'Premium Potato Sun Sunpreme','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (115,'Sugar','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (116,'Dry Pepper','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (117,'Hibiscus Flower','0','0','Herbs');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (118,'Flour Tortilla Medium and Small','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (119,'Mega Burrito Tortilla','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (120,'La Bandera Corn tortilla','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (121,'Cortan Fresh Baked bread','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (122,'20in Spaghetti','00','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (123,'Darum pasta','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (124,'DeCello lleva tappi','00','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (125,'smaller Pasta','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (126,'Food Service Black Nitril Gloves','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (127,'Shelter Folded Dispenser Napkins','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (128,'Ziploc Bags','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (129,'Foam Cups','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (130,'H and R Bleaches all purpose Flour','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (131,'Granulated salt','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (132,'Power flex garbage bag','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (133,'can liners','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (134,'Jumbosteaw First Mark','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (135,'Ancho','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (136,'Oil Sheets','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (137,'Sandwich wrap','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (138,'8\'\' Flour Tortilla','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (139,'Porion cub lids First mark','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (140,'Puritan cups First Mark','0','00','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (141,'Cold beverages lids 1 mle','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (142,'styrofoam food container','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (143,'togo boxes','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (144,'Nu york','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (145,'White Shrimps Freezer Cha,par','0','0','Seafood');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (146,'Champar','0','0','Seafood');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (147,'pork chops','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (148,'sweet plantain','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (149,'pork belly','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (150,'Fresh hard grated cheese','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (151,'White Hoagie roll','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (152,'Butter revaon ice cream','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (153,'Texas Toast','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (154,'Whole grain bearns','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (155,'Roman Parmesean','0','0','Dairy');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (156,'Acient Grains','0','00','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (157,'octopus','0','0','Seafood');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (158,'Argentino Chorizo','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (159,'Buffalo Dip','0','00','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (160,'New York cheesecake','0','0','Delites');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (161,'Enriched Bread','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (162,'French Fries','0','00','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (163,'Mozz cheese sticks','0','0','Processed food');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (164,'Sangria','0','0','Alcohol');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (165,'Fresa','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (166,'Squirt','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (167,'White Zombie','0','0','Alcohol');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (168,'Dos Equis','0','0','Alcohol');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (169,'Pina Colada Mix','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (170,'Peach Mix','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (171,'Strawberry Mix','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (172,'Clemay Mego','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (173,'Strawberry Puree','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (174,'Peach Puree','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (175,'Warchesire Puree','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (176,'Blueberries','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (177,'Hersy\'s chocolate syrup','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (178,'Whip Cream','0','0','Delites');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (179,'Blackberries','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (180,'kalamata olives','0','0','Fruits');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (181,'blackberry Sauce','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (182,'memolada','0','0','Drinks');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (183,'Hersey Caramel syrup','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (184,'1 Gal Windex','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (185,'windex bottle','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (186,'Matador Oven and Grill cleaner 32','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (187,'Members mark lemon disenfectant cleaner','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (188,'First Mark Hand soap','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (189,'Scothc Brite','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (190,'bleach','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (191,'West creek chicken breast','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (192,'West Creek Chicken Wings','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (193,'Tomato Puree','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (194,'First mark glove Nitirl','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (195,'West Creek fries','0','0','Grains');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (196,'Beef','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (197,'West Creek ketchup','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (198,'First Mark Napkins','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (199,'West Creek chicken Breast Jumbo','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (200,'Disposable Urinal Mat','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (201,'West Creek chicken winfs 1st and 2nd Jumbo','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (202,'Silver source bacon','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (203,'silversource sour cream','0','0','Sauces');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (204,'Granulated Sugar','0','0','Spices');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (205,'cake red velvet mint','00','0','Delites');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (206,'Doradees beef T-bone steak','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (207,'Tyson chicken strips','0','0','Meat');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (208,'Tissue Toilet','0','0','Supplies');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (209,'Brocoli','0','0','Vegetables');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (210,'Cake tux bomb mint','0','0','Delites');
INSERT INTO `` (`idInventory`,`item_name`,`price`,`amount`,`type`) VALUES (211,'Motts juice clamato pet','0','0','Drinks');
